title: VueLayers
description: VueLayers - Vue 2 components to work with OpenLayers
google_analytics: ''
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
  - jekyll-redirect-from
